//Language
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

//Cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const EMPTY_CART = 'EMPTY_CART'
export const RESET_PRICE = 'RESET_PRICE'

//counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const RESET_COUNTER = 'RESET_COUNTER'